name: Hcu-Build-And-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hcu-build-and-test:
    runs-on: hcu
    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Setup environment
        shell: bash
        run: |
          source ~/env.sh
          env | grep -E '^(http_proxy|https_proxy|all_proxy|no_proxy)=' >> $GITHUB_ENV || true

      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: Check if only docs files changed
        id: check_files
        uses: flagos-ai/FlagTree/.github/actions/check-docs-only@main

      - name: FlagTree Build on Hcu
        if: steps.check_files.outputs.only_docs_changed != 'true'
        shell: bash
        run: |
          set -x
          pip uninstall -y triton
          export FLAGTREE_BACKEND=hcu
          cd python
          MAX_JOBS=32 python3 -m pip install . --no-build-isolation

      - name: FlagTree Test on Hcu
        if: steps.check_files.outputs.only_docs_changed != 'true'
        shell: bash
        run: |
          set -x
          cd third_party/hcu/python/test/unit
          sh flagtree_test.sh
